### PR TITLE
Group 1 Project

### PR DESCRIPTION
**Pull request by Alanatusa**

### CODE REVIEW

**Comment by lizzzi111** [comment]
Dear group, 
please check that your metafile is YAML debuggable - the ' in the end of the name of quantlet is missing.
The main coding script should have the same name as stated in the metainfo.txt
If you have multiple important scripts (that do different functionality or step ) - it is possible that you need to divide your projects into multiple folders/quantlets.
Thanks.
Best,
Liza from Q Team

**Comment by Alanatusa** [comment]
ok, I revised that. Thank you

Elizaveta Zinovyeva ***@***.***>于2021年4月15日 周四下午3:38写道：

**Comment by lizzzi111** [comment]
Dear group,
I will repeat the second part of my comment:
The main coding script should have the same name as stated in the metainfo.txt
If you have multiple important scripts (that do different functionality or step ) - it is possible that you need to divide your projects into multiple folders/quantlets.
Thanks.
Best,
Liza from Q Team

**Comment by lizzzi111** [comment]
By the way - if you need help or have questions - just let me know.

**Comment by Alanatusa** [comment]
Hi, I revised it again, can you check it? Thank you.

Elizaveta Zinovyeva ***@***.***>于2021年4月15日 周四下午4:41写道：

**Comment by lizzzi111** [comment]
Dear group,
your folder looks good. The next time please do not delete files outside your folder.
Thank you.
Best. Liza

**Pull request closed without merging**
