### PR TITLE
pull request for Group3 project

### PR DESCRIPTION
**Pull request by manoposunqingwei**

### CODE REVIEW

**Comment by lizzzi111** [comment]
Dear students, please check, that the main script of the quantlet has the same name as the Quantlet name field specified in the Metainfo.txt. E.g If Quantlet name is StockCorr_Data_Downloader then the main script needs to have the name StockCorr_Data_Downloader.py (or .ipynb .r - depending on what language and IDE you used) If you have questions - please write in the comment below. Best, Liza from Q Team

**Comment by manoposunqingwei** [comment]
Thank you so much for the comment @lizzzi111! I have updated the main script name accordingly. Please kindly check. In addition, we put StockCorr_Clustering_Analysis.ipynb and StockCorr_Clustering_Analysis.py under  StockCorr_Clustering_Analysis folder, not sure whether that is ok. Kindly let me know. Thank you again.

**Comment by manoposunqingwei** [comment]
Thank you @lizzzi111!

**Comment by lizzzi111** [comment]
You're welcome :)

**Pull request merged**
