### PR TITLE
Project Group8

### PR DESCRIPTION
**Pull request by wyz1160084961**

### CODE REVIEW

**Comment by lizzzi111** [comment]
Dear group, 
stylistically it looks good (I did not check whether everything works, just looked on te formatting).
A couple of  comments: could you please rename your main script - it should have the same name as the Quantlet name specified in the Metainfo.txt For example for GUBA_crawl the main.py should renamed into GUBA_crawl.py

And metainfo.txt should lie in the same folder as the main script. E.g. backtestlite.py - you need to move metainfo.txt into the same folder as this file is or vice versa.

Best, 
Elizaveta from the Q team

**Comment by lizzzi111** [comment]
Dear group, 

I forgot to add to the last comment. The keyword field needs to have at least 5 keywords. Otherwise the README won't be created. Sorry, that I forgot to mention it in the last comment.

Best, 
Liza.

**Comment by wyz1160084961** [comment]
Hi Liza,

Thanks for you comment, I have fixed them.

Best wishes,
Yuzhou

**Comment by lizzzi111** [comment]
Great, looks good, I accept the request

**Pull request merged**
